SELECT TOP (1000) [Fecha]
      ,[Inicio_Mes]
      ,[Fin_Mes]
      ,[SemestreNom]
      ,[SemestreNum]
      ,[Trimestre_Num]
      ,[Trimestre]
      ,[NombreMes]
      ,[MesNo]
      ,[QuincenaNum]
      ,[QuincenaNom]
      ,[Semana]
      ,[Día]
      ,[DiaSemana]
      ,[NombreDíaSemana]
      ,[Mes]
      ,[NumMes]
      ,[Año]
      ,[Año_Mes]
      ,[Año_Mes_Mes]
      ,[Año_MesNo]
      ,[Año_NombreMes]
      ,[SemanaFlujo]
      ,[Año_Mes_Semana]
      ,[TipoCambio]
      ,[CierreFiscal]
      ,[AñoFiscal]
  FROM [BI].[GLOBALES].[vwCalendarTable]